version: "3.5"

services:
  build-registry:
    image: registry
    ports:
      - 5001:5001
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5001
    volumes:
      - ./build/registry:/var/lib/registry
